/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "weatherCS_constants.h"



const weatherCSConstants g_weatherCS_constants;

weatherCSConstants::weatherCSConstants() {
}



