/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef weather_CONSTANTS_H
#define weather_CONSTANTS_H

#include "weather_types.h"



class weatherConstants {
 public:
  weatherConstants();

};

extern const weatherConstants g_weather_constants;



#endif
