/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef weatherCS_CONSTANTS_H
#define weatherCS_CONSTANTS_H

#include "weatherCS_types.h"



class weatherCSConstants {
 public:
  weatherCSConstants();

};

extern const weatherCSConstants g_weatherCS_constants;



#endif
