#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class SortMethod:
  Up = 0
  Down = 1

  _VALUES_TO_NAMES = {
    0: "Up",
    1: "Down",
  }

  _NAMES_TO_VALUES = {
    "Up": 0,
    "Down": 1,
  }


class weather_info:
  """
  Attributes:
   - city_id
   - name
   - max_temp
   - min_temp
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'city_id', None, None, ), # 1
    (2, TType.STRING, 'name', None, None, ), # 2
    (3, TType.I32, 'max_temp', None, None, ), # 3
    (4, TType.I32, 'min_temp', None, None, ), # 4
  )

  def __init__(self, city_id=None, name=None, max_temp=None, min_temp=None,):
    self.city_id = city_id
    self.name = name
    self.max_temp = max_temp
    self.min_temp = min_temp

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.city_id = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.name = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.max_temp = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.min_temp = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('weather_info')
    if self.city_id is not None:
      oprot.writeFieldBegin('city_id', TType.STRING, 1)
      oprot.writeString(self.city_id)
      oprot.writeFieldEnd()
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 2)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.max_temp is not None:
      oprot.writeFieldBegin('max_temp', TType.I32, 3)
      oprot.writeI32(self.max_temp)
      oprot.writeFieldEnd()
    if self.min_temp is not None:
      oprot.writeFieldBegin('min_temp', TType.I32, 4)
      oprot.writeI32(self.min_temp)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
